### ISSUE TITLE
Any plans to support Datasets?

### ISSUE THREAD

**Issue by e-abreu** [dotnet/spark#103]
Looking at the code and the roadmap, there is nothing about supporting Datasets in the future.
Are there any plans for it?

---

Dataframes are the untyped version of the Dataset (Dataset<Row>).
Datasets would allow writing less code and code less prone to bugs, using Spark as one would use Linq.

I'm talking about coding in C# using this:
```
Dataset<Person> dataset;
dataset.Filter(p => p.Age >= 18).Select(p => p.Name)
```

Over this:
```
Dataframe dataframe;
dataframe.Filter("Age >= 18").Select("Name")
```

**Comment by rapoth** [comment]
@e-abreu: As it turns out, this is one of the current limitations of Apache Spark. We started looking into this but after checking with the Apache Spark community and looking at what PySpark folks are doing, we were advised against opening up Dataset API. The recommendation from Apache Spark is to not really depend on Datasets API in other languages.

Beyond this, there are a few practical problems. While the Datasets API is very cool in Scala, it is fundamentally a pain in the context of multiple languages. For instance, although you could define a (serializable) C# class, to get it actually running in Spark, you would also need to provide ser/de logic in Java (and consider what happens if you ever want to access or write your code in Python). If you do not provide the ser/de logic in Java, Spark cannot compute its own internal functions over the byte array (e.g., when the data is getting processed inside JVM side of Spark). Here's a diagram to explain this:

```
                              Serialize               Serialize                      
Custom Input ----------> JVM ---------------> CLR -----------------> JVM ---------------------> Output
                          |                     |                       |
                          V                     V                       V
                    Read and deserialize      Read & deserialize      Read & deserialize
                    into JVM objects           into CLR objects        into JVM objects
                      (user-provided)           (user-provided)         (user-provided)
```

If this is a deal breaker, I would highly recommend mailing the Spark dev list to get their suggestions (and feel free to CC us -  we are happy to provide support if Spark itself has a recommended way of how we could achieve it).

Note: I'm closing this issue for now, but feel free to re-open if you have any ideas on how we could implement this in the current framework of Apache Spark. Thank you!
