### ISSUE TITLE
'spark-submit' is not recognized as an internal or external command error

### ISSUE THREAD

**Issue by schinchanikar-rms** [dotnet/spark#268]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by imback82** [comment]
Can you try `%SPARK_HOME%\bin\spark-submit`? 

cc: @bamurtaugh

**Comment by bamurtaugh** [comment]
@schinchanikar-rms Was your issue specifically on the "Install Apache Spark" step? If so, which part, and what was your error/problem?

**Comment by schinchanikar-rms** [comment]
I did resolve my issue. The issue was that there is a line missing in the online instructions. The missing line is Setting of Path environment variable. I caught it in the video and ran it and now everything works fine.

Thanks,
Suchi

**Comment by bamurtaugh** [comment]
Great, glad you were able to resolve your issue @schinchanikar-rms. When you say you caught it in the video, was it something that was said in one of the .NET for Apache Spark 101 videos specifically?

**Comment by schinchanikar-rms** [comment]
Yes. In one of the Spark 101 videos there was a path variable set.

**Comment by bamurtaugh** [comment]
Awesome, glad it helped @schinchanikar-rms! Was it the `DOTNET_ASSEMBLY_SEARCH_PATHS` variable?

**Comment by schinchanikar-rms** [comment]
No in Set environment variables in https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
There was one more line that was in the video. It was PATH variable. I had missed that.

**Comment by bamurtaugh** [comment]
Okay, thank you for elaborating! It should work if you modify the PATH, or if you use the command `%SPARK_HOME%\bin\spark-submit` when you run spark-submit (even if you don't set your PATH). 😄

**Comment by schinchanikar-rms** [comment]
Ok. Will try that. Thanks.

**Comment by bamurtaugh** [comment]
@schinchanikar-rms You're welcome! Please keep us posted if it works and if you have any further questions.

@imback82 I think we also need to update the last command on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark to say: `%SPARK_HOME%\bin\spark-submit --version`, since we've decided to no longer include changing the path. @rowanmiller Can you help us with this? 😃

**Comment by schinchanikar-rms** [comment]
Is it possible to create Dataframe using SQL database tables? I could not find an example.
Could you please point me to an example of getting a dataframe created from SQL database?

**Comment by bamurtaugh** [comment]
@imback82 @rapoth Do you have any examples of creating a Dataframe using SQL database tables?

**Comment by rapoth** [comment]
@schinchanikar-rms: We see you are attempting to use JDBC to read from SQL Server in https://github.com/dotnet/spark/issues/271 Let's discuss how to resolve this problem in that issue. 

@bamurtaugh Just an FYI that as per instructions here: [Ubuntu](https://github.com/dotnet/spark/blob/master/docs/building/ubuntu-instructions.md#pre-requisites), [Windows](https://github.com/dotnet/spark/blob/master/docs/building/windows-instructions.md#pre-requisites) and also the [Online Instructions](https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark), we did capture that `SPARK_HOME` should be added to the environment variables.

**Comment by bamurtaugh** [comment]
@rapoth Thanks for the clarification! Maybe I am missing a step, but when users call `spark-submit` now, since we no longer add `spark-submit` to the path (in a recent issue, we decided to no longer modify the path), we can't just call `spark-submit` as-is.

We now instead call `%SPARK_HOME%\bin\spark-submit`. We reflected this change in the [last page of the online tutorial](https://dotnet.microsoft.com/learn/data/spark-tutorial/run) but not in the example of calling `spark-submit` [here](https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark), so I thought we'd still potentially need an update to say `%SPARK_HOME%\bin\spark-submit` in the final command on that page? 

My apologies if I'm misunderstanding something!

**Comment by schinchanikar-rms** [comment]
I am using the following code to load the SQL table into the dataframe:

DataFrame dataFrame = spark.Read().Format("jdbc").Option("url", "jdbc:sqlserver://localhost;databaseName=TEST_DB;integratedSecurity=true;")
                .Option("driver", "com.Microsoft.SqlServerDriver")
                .Option("dbtable", "Address")
                .Load();

**Comment by rapoth** [comment]
@schinchanikar-rms Can you respond in your other thread please? That way, we can keep this thread within topic (which is spark-submit) and not mix up our responses :)

**Comment by rapoth** [comment]
@bamurtaugh Sorry, I missed that thread where we decided to no longer modified path. I misunderstood. The docs on GitHub are correct but I guess the point you are making is a change on that tutorial, which is valid.

I'm going to go ahead and close the issue. Please feel free to re-open if you are not satisfied with the resolution.

**Comment by rowanmiller** [comment]
> @imback82 I think we also need to update the last command on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark to say: %SPARK_HOME%\bin\spark-submit --version, since we've decided to no longer include changing the path. @rowanmiller Can you help us with this? 😃

I've kicked off this change to the tutorial. @bamurtaugh & @imback82 I've included you as reviewers.

**Comment by Jiacheng-Li** [comment]
> Okay, thank you for elaborating! It should work if you modify the PATH, or if you use the command `%SPARK_HOME%\bin\spark-submit` when you run spark-submit (even if you don't set your PATH). 😄

Hi Brigit

I also got stuck at this stage since I always get "The system cannot find the path specified". I am pretty sure I set the environment variables correctly and placed the files in the right directory. Would you mind helping me with it?
Thanks!
![Path not found](https://user-images.githubusercontent.com/53215260/85220784-6ba2dd00-b3a6-11ea-88db-a1af015c26f5.PNG)
![Environment Varible](https://user-images.githubusercontent.com/53215260/85220811-95f49a80-b3a6-11ea-8fc5-6feb6374f0eb.PNG)
![dir](https://user-images.githubusercontent.com/53215260/85220851-d5bb8200-b3a6-11ea-8b93-b502ccdd0f6b.PNG)

**Comment by suhsteve** [comment]
@Jiacheng-Li  can you do an `echo %SPARK_HOME%` ?  Your environment variable may not be set up correctly or you need to restart your command prompt.
