### ISSUE TITLE
Which demo code is standard code for structured streaming? 

### ISSUE THREAD

**Issue by liangb4009** [dotnet/spark#309]
[Program.zip](https://github.com/dotnet/spark/files/3781820/Program.zip)

[result.txt](https://github.com/dotnet/spark/files/3776927/result.txt)
The **code in structure streaming demo video** has great difference with Github streaming demo code, **May I know which one is the standard code?** 
If the structured stream demo video code as the standard code, it will return error message, the error message will be like "result.txt";
If the Github streaming demo code as the standard code, it will not pass the compiling process, the error message will find "the defination of IExample", May I know the defination of "IExample", And How could I compile and use the Github stream demo code?
**The stream demo video**
https://channel9.msdn.com/Series/NET-for-Apache-Spark-101/Structured-Streaming-with-NET-for-Apache-Spark
The stream demo video code, see attachment which name is "Program.cs"
**The code in Github stream demo code**
https://github.com/dotnet/spark/blob/master/examples/Microsoft.Spark.CSharp.Examples/Sql/Streaming/StructuredNetworkWordCount.cs

**Comment by bamurtaugh** [comment]
Hi @liangb4009 - thanks for your question. 

There isn't necessarily one "standard code" for structured streaming - as long as you have a Spark Session, use ReadStream() with a DataFrame, and WriteStream() with a StreamingQuery, you have the fundamental elements of a structured streaming app. Out of those 2 examples, the code in GitHub is probably the most "standard" since it's based on a pre-established Python streaming example (as it says at the top of that example: `The example is taken/modified from spark/examples/src/main/python/sql/streaming/structured_network_wordcount.py`).

Can you elaborate on how you ran both programs? For both the demo video and GitHub demo code, the first streaming sources it's recommended to try them out with is netcat (I explained some of this in a [readme](https://github.com/bamurtaugh/spark/tree/samples-cleanup/examples/Microsoft.Spark.CSharp.Examples/Streaming)).

For running the GitHub demo code, are you following either the Windows or Ubuntu build instructions [here](https://github.com/dotnet/spark/tree/master/docs/building)? IExample helps keep some standard formatting/protocol across examples, and if you try to run an app using IExample in a separate app rather than following the build instructions linked to above, you'll probably face that error about finding the IExample definition.

**Comment by imback82** [comment]
Please reopen the issue if @bamurtaugh's response didn't answer your question.
