### ISSUE TITLE
[FEATURE REQUEST]: Job Cancellation

### ISSUE THREAD

**Issue by michael-damatov** [dotnet/spark#427]
**Is your feature request related to a problem? Please describe.**
With Databricks I'm always able to _cancel_ a job. Is such a case I would like to get notified when the process is about to be closed or killed.

**Describe the solution you'd like**
A _cancellation token_ that is signaled when the job is canceled. The cancellation token can be used to cancel internal tasks.

**Comment by imback82** [comment]
@michael-damatov Can you check which signal gets sent (or what behavior you see) to `DotnetRunner` (scala) when a job is cancelled in Databricks? You can check #424 description, and if `process.destory` is called, you can handle it via `AppDomain.CurrentDomain.ProcessExit`.

**Comment by michael-damatov** [comment]
@imback82 Do I need v0.9.0? Or the observed behavior should be the same with v0.8.0?

**Comment by imback82** [comment]
#424 is a part of v0.9.0, so please try with v0.9.0.

**Comment by imback82** [comment]
@michael-damatov did you get a chance to try this?

**Comment by michael-damatov** [comment]
@imback82 I've tried this with 0.10.0. The `AppDomain.CurrentDomain.ProcessExit` event is **not** signaled when I cancel the job in Databricks.

**Comment by imback82** [comment]
@tylorhl Do you happen to know how to propagate the "cancellation" message to C# process in Databricks?

**Comment by tylorhl** [comment]
@imback82 It should be caught with `AppDomain.CurrentDomain.ProcessExit` as you mentioned. This has been working reliably for me.

@michael-damatov What's your test for checking if the registered `ProcessExit` event was fired? Something to note is that writing to `Console` will not work once `process.destroy` has been called as Java closes stdin, stdout, and stderr for `process` immediately after sending the termination signal without waiting for the process to terminate.

**Comment by michael-damatov** [comment]
@tylorhl  I've seen the notes in #424 about closed standard streams, so I'm trying to create a new empty blob in a blob storage when the `ProcessExit` event is fired. Any idea how else could I test this?

**Comment by tylorhl** [comment]
@michael-damatov When I needed to verify that it was working, I was having my `ProcessExit` event just write an arbitrary string to a file under `/dbfs/` via `File.WriteAllText(string,string)`. It worked well both for me testing #424 and after uptaking the 0.9.0 release in a project.

**Comment by michael-damatov** [comment]
@tylorhl now I see that the `ProcessExit` event is fired. However, I wanted to see how much time would I have to cancel my routines, so I've used the event handler (s. below), just to see how far it comes. The method should create a new file every 100 ms.

As a result I only see the `/dbfs/mytemp/process_exit_0` file created. **Is the conclusion correct that I only have less than 100 ms?**

``` c#
private static async void CurrentDomain_ProcessExit(object sender, EventArgs e)
{
    File.WriteAllText("/dbfs/mytemp/process_exit_0", "");
    for (int i = 1; i <= 200; i++)
    {
        await Task.Delay(100).ConfigureAwait(false);
        File.WriteAllText("/dbfs/mytemp/process_exit_" + i.ToString(), "");
    }
}
```

**Comment by tylorhl** [comment]
@michael-damatov My guess is that it's because the handler is async, though I haven't tested it. Once `ProcessExit` has finished firing all registered handlers, the process will exit. In the case of your code snippet, being `async void`, my guess is that `ProcessExit` finishes once `await` is hit. What happens if you change `await Task.Delay(100).ConfigureAwait(false)` to `Task.Delay(100).GetAwaiter().GetResult()` and removed the `async` keyword from the signature?

**Comment by michael-damatov** [comment]
@tylorhl Thanks for the tip, now I see that the `ProcessExit` method is running for ca. 5 full seconds and is interrupted between the 5th and 6th second (as promised). 👍

The next question is after I've got a signaled cancellation token whether I could stop a long running task like writing a data frame to DBFS `dataFrame.Write().Save(...)`. Or should I just let the process die (so the "write" operation will also be interrupted)?

**Comment by tylorhl** [comment]
@michael-damatov Glad it worked out 😁

Unfortunately I don't have a good answer as far as cancelling a call to Spark goes. Since those calls are delegated to the JVM, there isn't much that can be done on the .NET side unless Spark decides to add some asynchronous cancellation mechanism for `dataFrame.Write().Save(...)`. My best suggestion would be to check on a `CancellationToken` for a cancellation just before calling `dataFrame.Write().Save(...)` and hope for the best.

Alternatively, if it fits your scenario, you may be able to implement something to cancel a Structured Streaming setup, since that runs asynchronously and can be stopped. I haven't done it myself and I'm no expert in using the various Spark APIs, but something along the lines of this might work as an extension method to accomplish your example:
```csharp
public static void Save(this DataFrame dataFrame, string path, CancellationToken cancellationToken)
{
    var streamingQuery = dataFrame
        .WriteStream()
        .Format("parquet")
        .Option("path", path)
        .Trigger(Trigger.Once())
        .Start();

    // Calls streamingQuery.Stop() when cancellation occurs on the token
    using (var cancellationRegistration = cancellationToken.Register(streamingQuery.Stop))
    {
        streamingQuery.AwaitTermination();
    }
}
```

**Comment by michael-damatov** [comment]
@tylorhl When I cancel a job, the Databricks also cancels JVM operations, so it works as expected. 

Regarding the data consistency: interrupting the "write" operation using the _delta_ format does not break the data (the new version is simply not committed).
