### ISSUE TITLE
No Connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by briancuster** [dotnet/spark#521]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/code
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I tried to run the code sample for the .net Spark app and got an error message saying that System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: 'No connection could be made because the target machine actively refused it. 127.0.0.1:5567'

**Comment by suhsteve** [comment]
When you ran your app, did you run just your C# binary or did you try running it using `spark-submit` ?

**Comment by imback82** [comment]
@briancuster, Please check #395, #175. Thanks.

**Comment by linehammer** [comment]
This exception message says you're trying to connect to the same host ( 127.0.0.1 ), while you're stating that your server is running on a different host. This 127.0.0.1 represents a 'loopback' . It allows the computer to communicate with itself via network protocol .

Dns.GetHostEntry(IPAddress.Loopback).HostName returns the host name of your machine. When you pass a host name to TcpClient , it will resolve it to one or more IP addresses using Dns.GetHostAddresses(hostName) . This includes the public and local IP addresses of your machine (e.g. 192.168.12.10), but not 127.0.0.1 (loopback address). So your client is trying to connect to any of the non-loopback addresses of your machine, while your server is listening only on the loopback address . So, [no connection](http://csharp.net-informations.com/communications/connection.htm) can be established. The solution to this problem is that connect to the same end point your server is listening on.

**Comment by Niharikadutta** [comment]
@briancuster were you able to get this issue resolved?

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
