### ISSUE TITLE
Run dotnet DLL in release mode

### ISSUE THREAD

**Issue by JavierLight** [dotnet/spark#568]
I'm wondering if it's possible to run a compiled dotnet DLL (using code from this library) without the need of setting up the DotnetRunner debug port spark process.

I could not find in the docs if there's a way to run this in a "release" mode or if it's even possible at all to run my app using dotnet instead of spark-submit.

In order to give you more context, imagine you have a REST API implemented in .NET that ends calling a method that via `dotnet-spark` creates a spark session and executes some spark method.

Running `dotnet MyApp.dll` fails because the port 5567 is not listening (I'm not trying to debug the app, just to execute it). Is this something designed like this on purpose? I know the easy solution would be to run spark-submit debug using the DotnetRunner class, but I don't think it makes any sense if I don't want to debug.

Thank you very much for your time :)

**Comment by Niharikadutta** [comment]
Hi @JavierLight thank you for your question. There is no way to locally submit a .NET for Apache Spark application without using `spark-submit`, since that is the command to submit a Spark batch job and it expects a jar (`microsoft-spark-<version>.jar`) which is the entry point to which the dotnet application attaches and interacts with in order to translate the data/code between the JVM and CLR. You can however submit a dotnet application using `dotnet app.dll` to the spark-submit command in place of the executable (You don't need to setup a debug process).
However, if you are looking to submit a job to a remote Spark cluster through a REST API, you can use [Apache Livy](https://livy.apache.org/) which is a REST service to submit and track Spark jobs. Please take a look at [this guide](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/hdinsight-deploy-methods#deploy-using-apache-livy) to see how to submit a .NET for Apache Spark job to an HDInsight Spark cluster (The procedure would be similar to any other cloud/remote Spark cluster).

**Comment by JavierLight** [comment]
Thanks for the clarification!
