### ISSUE TITLE
[FEATURE REQUEST]: Support ArrayList / Hashtable udf chaining

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#684]
Allow chaining of udf calls such as

```csharp
udf1 = Udf<string, ArrayList>(..)
udf2 = Udf<ArrayList, string>(..)

udf2(udf1(..))

udf3 = Udf<string, Hashtable>(..)
udf4 = Udf<Hashtable, string>(..)

udf4(udf3(..))
```

**Comment by Niharikadutta** [comment]
Since `ArrayList` and `HashTable` are non-generic collections, I am unable to derive their element types in [`GetReturnType`](https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Utils/UdfUtils.cs#L130) to create the corresponding `ArrayType` and `MapType` json string as needed by [`UserDefinedFunction`](https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Sql/Expressions/UserDefinedFunction.cs#L41). Please let me know if there is another way to do this or if I am missing something. Thanks!

**Comment by suhsteve** [comment]
At the time of UDF creation, we only have the `Type` object of `ArrayList` and `HashTable` and not object instances of these classes.  We don't have enough information to inform spark that it is a `ArrayType/MapType` since those are require element/key/value type information.

We may be able to do this if we explore `udt`s but not sure if that's the approach we want to take.  @imback82 thoughts ?

**Comment by Niharikadutta** [comment]
Closing this as this cannot be supported.
