### ISSUE TITLE
Log redirection issue on DotnetRunner

### ISSUE THREAD

**Issue by clegendre** [dotnet/spark#770]
https://github.com/dotnet/spark/blob/b8e2259bcf81ea82bb0827321664ebb6889ba56b/src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala#L128

Shouldn't be getInputStream here

https://github.com/dotnet/spark/blob/b8e2259bcf81ea82bb0827321664ebb6889ba56b/src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala#L130

And getOutputStream here ?

**Comment by imback82** [comment]
@clegendre Can you elaborate what's wrong here? Please check this for `getInputStream`: https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#getInputStream--  . For example, `getIntputStream` returns `the input stream connected to the normal output of the subprocess.` so that the parent process can consume the stream.

**Comment by clegendre** [comment]
You might have right, I've been disappointed by the logs on Azure Synapse Spark which shows the whole output logs on **stderr**. 
So it must be an issue on Synapse Spark.

![image](https://user-images.githubusercontent.com/1580277/98592803-841e8000-22d2-11eb-89d8-227f2ad55ae0.png)

**Comment by imback82** [comment]
These logs in `stderr` are normal (you can check HDInsight and Databricks. Only the outputs from your application (e.g., `Console.WriteLine`) should land in `stdout`.

**Comment by clegendre** [comment]
Oh OK, thanks for the clarification!
