### ISSUE TITLE
[BUG]: IsIn Function not in API Docs

### ISSUE THREAD

**Issue by lqdev** [dotnet/spark#776]
**Describe the bug**

`IsIn` function is not in API Docs.

https://github.com/dotnet/spark/blob/38531dee4a3f508c398ebb0a69fd922213ae6492/src/csharp/Microsoft.Spark/Sql/Column.cs#L770

**To Reproduce**

Go to docs and search / browse for `IsIn`.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.spark.sql.column?view=spark-dotnet

**Comment by Niharikadutta** [comment]
Thanks @lqdev for reporting this issue. I verified there are more APIs that are exposed as part of the latest v1.0.0 that have not made it to the API documentation yet (Such as `DataFrame` APIs: `ToJson()`, `Explain(String mode)`, `Observe()` etc.) and I wonder if it might be because they haven't synced with the latest `Microsoft.Spark` version yet. I checked the reference documentation for all these APIs and I don't think this is an issue in our code, but please feel free to open an issue with https://github.com/MicrosoftDocs/feedback/issues and ask about their syncing cadence with latest versions of SDKs released.

**Comment by Niharikadutta** [comment]
Thanks for reporting this and working on getting the v1.0.0 nuget updated with the .NET API browser @lqdev ! Closing this issue as it has been resolved.
