### ISSUE TITLE
Is this project still active/alive?

### ISSUE THREAD

**Issue by daxnet** [dotnet/spark#974]
Just curious about whether this project is still maintained or still alive? It seems it's been around 3 months since last commit on the main branch.

**Comment by MikeRys** [comment]
Hi Sunny

The project is still around and alive. Since we released version 2.0, the cadence has slowed down a bit, since we have mostly caught up with the capabilities. There is now Spark v3.2 pending that may bring some updates.

The project itself is currently also ships out of the box in Azure HDInsight Spark and Azure Synapse Spark, so it will continued to be maintained.

What specific scenarios are you interested in?

Best regards
Michael

From: Sunny Chen ***@***.***>
Sent: Wednesday, September 22, 2021 9:42 PM
To: dotnet/spark ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/spark] Is this project still active/alive? (#974)


Just curious about whether this project is still maintained or still alive? It seems it's been around 3 months since last commit on the main branch.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fspark%2Fissues%2F974&data=04%7C01%7Cmrys%40microsoft.com%7C764c0048480741934aa508d97e4c8183%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637679689332490798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=478ag3CRZPUaqpof2TaJkvTrnih2rky0aBDiljuneUE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZXGJEX5PNZBBTJM4Q6FWTUDKV2FANCNFSM5ESZUPYQ&data=04%7C01%7Cmrys%40microsoft.com%7C764c0048480741934aa508d97e4c8183%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637679689332500794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3fmShX38a2LZ0l6eZF%2BTUwm6uUqBle3k%2FxQFEYkdJrA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmrys%40microsoft.com%7C764c0048480741934aa508d97e4c8183%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637679689332500794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kv%2FJFgfbuOdBf3lxsXK4Shabnmj6pgUoJsIAfmGFa7w%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmrys%40microsoft.com%7C764c0048480741934aa508d97e4c8183%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637679689332510789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2dazKSBR5MZLp78RLz54djbiO4CBAHfs%2B2TWXUiHZks%3D&reserved=0>.

**Comment by rrekapalli** [comment]
Hi @MikeRys,

Good to hear that this project is still alive!  This library is a wonderful fit for one of our project.  However,  had to consider alternatives as there have been no updates especially on the ML side of this library.  Are there any plans to provide complete support for the SparkML / MLLib.  Would be great if there's any tentative timelines for the same.

Regards

**Comment by daxnet** [comment]
Hi @MikeRys 
Thanks so much for answering my question. I think .NET for Spark is a great project and I also used it as a default provider of the Data Factory platform that I created and built by myself, if you are interested, you can refer to my project here: [https://github.com/daxnet/abacuza](https://github.com/daxnet/abacuza).
Just as @rrekapalli  mentioned, I also would like to explore more about the ML features of this library. But anyways, it is wonderful that the project is still alive and will be continuously supported.
Thank you.
/Sunny
